/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.diego.xlanches.forms;

import com.diego.xlanches.dao.ItemCaixaDAO;
import com.diego.xlanches.dao.ProdutoDAO;
import com.diego.xlanches.data.ItemCaixa;
import com.diego.xlanches.data.ItemCaixaTableModel;
import com.diego.xlanches.data.Produto;
import com.diego.xlanches.data.ProdutoTableModel;
import java.awt.BorderLayout;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;
import java.util.stream.Collectors;
import javafx.scene.input.MouseButton;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.TableColumnModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author vinicius.fatala
 */
public class MainForm extends javax.swing.JFrame {

	public static final Locale ptBR = new Locale("pt", "BR");
	/**
	 * Creates new form MainForm
	 */
	public MainForm() {
		initComponents();
		
		TableColumnModel tb_caixa_model = tb_caixa.getColumnModel();
		tb_caixa_model.getColumn(0).setPreferredWidth(25);
		tb_caixa_model.getColumn(1).setPreferredWidth(200);
		tb_caixa_model.getColumn(2).setPreferredWidth(25);
		tb_caixa_model.getColumn(3).setPreferredWidth(50);
		
		TableColumnModel tb_produtos_model = tb_produtos.getColumnModel();
		tb_produtos_model.getColumn(0).setPreferredWidth(25);
		tb_produtos_model.getColumn(1).setPreferredWidth(200);
		tb_produtos_model.getColumn(2).setPreferredWidth(25);
		
		tx_valor.setFormatterFactory(
				new DefaultFormatterFactory(
						new NumberFormatter(NumberFormat.getCurrencyInstance(ptBR)),
						new NumberFormatter(NumberFormat.getCurrencyInstance(ptBR)),
						new NumberFormatter(NumberFormat.getNumberInstance())
				)
		);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pm_tablecell_produtos = new javax.swing.JPopupMenu();
        mn_delete = new javax.swing.JMenuItem();
        pm_tablecell_caixa = new javax.swing.JPopupMenu();
        mn_delete_cx = new javax.swing.JMenuItem();
        tabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bt_add = new javax.swing.JButton();
        sp_produtos = new javax.swing.JComboBox<>();
        sp_qtd = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_caixa = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tx_total = new javax.swing.JLabel();
        bt_fechar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bt_add1 = new javax.swing.JButton();
        tx_valor = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        tx_pnome = new javax.swing.JTextField();
        tx_pdesc = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_produtos = new javax.swing.JTable();

        mn_delete.setText("Deletar");
        mn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_deleteActionPerformed(evt);
            }
        });
        pm_tablecell_produtos.add(mn_delete);

        mn_delete_cx.setText("Deletar");
        mn_delete_cx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_delete_cxActionPerformed(evt);
            }
        });
        pm_tablecell_caixa.add(mn_delete_cx);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabs.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabsStateChanged(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        java.awt.GridBagLayout jPanel3Layout = new java.awt.GridBagLayout();
        jPanel3Layout.columnWidths = new int[] {200, 32, 32};
        jPanel3.setLayout(jPanel3Layout);

        jLabel2.setText("PRODUTO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 3);
        jPanel3.add(jLabel2, gridBagConstraints);

        jLabel1.setText("QTD.");
        jLabel1.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(8, 6, 0, 0);
        jPanel3.add(jLabel1, gridBagConstraints);

        bt_add.setText("+");
        bt_add.setToolTipText("Inserir");
        bt_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel3.add(bt_add, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel3.add(sp_produtos, gridBagConstraints);

        sp_qtd.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 3, 2, 3);
        jPanel3.add(sp_qtd, gridBagConstraints);

        jPanel1.add(jPanel3, java.awt.BorderLayout.NORTH);

        tb_caixa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "#", "PRODUTO", "QTD.", "VALOR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_caixa.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tb_caixa.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tb_caixa);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        jPanel4.setLayout(new java.awt.BorderLayout(6, 0));

        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.setPreferredSize(new java.awt.Dimension(560, 80));

        jLabel3.setText("TOTAL");

        tx_total.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        tx_total.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tx_total.setText("R$0,00");
        tx_total.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tx_total, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tx_total, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.add(jPanel5, java.awt.BorderLayout.CENTER);

        bt_fechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/diego/xlanches/res/check.png"))); // NOI18N
        bt_fechar.setText("FECHAR VENDA");
        bt_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_fecharActionPerformed(evt);
            }
        });
        jPanel4.add(bt_fechar, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        tabs.addTab("Caixa", new javax.swing.ImageIcon(getClass().getResource("/com/diego/xlanches/res/cash-multiple.png")), jPanel1); // NOI18N

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        jLabel5.setText("PRODUTO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 3);
        jPanel6.add(jLabel5, gridBagConstraints);

        jLabel6.setText("VALOR");
        jLabel6.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(8, 6, 0, 0);
        jPanel6.add(jLabel6, gridBagConstraints);

        bt_add1.setText("+");
        bt_add1.setToolTipText("Inserir");
        bt_add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_add1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel6.add(bt_add1, gridBagConstraints);

        tx_valor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel6.add(tx_valor, gridBagConstraints);

        jLabel7.setText("DESCRIÇÃO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanel6.add(jLabel7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel6.add(tx_pnome, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel6.add(tx_pdesc, gridBagConstraints);

        jPanel2.add(jPanel6, java.awt.BorderLayout.NORTH);

        tb_produtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "#", "NOME", "VALOR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_produtos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tb_produtos.getTableHeader().setReorderingAllowed(false);
        tb_produtos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_produtosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tb_produtos);

        jPanel2.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        tabs.addTab("Produtos", new javax.swing.ImageIcon(getClass().getResource("/com/diego/xlanches/res/food.png")), jPanel2); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabsStateChanged
		int tab = tabs.getSelectedIndex();
		switch (tab) {
			default:
				break;
			case 0: {
				final ArrayList<Produto> produtos = ProdutoDAO.get().select();
				sp_produtos.setModel(new DefaultComboBoxModel<>(produtos.toArray(new Produto[produtos.size()])));
				
				final ArrayList<ItemCaixa> itens = ItemCaixaDAO.get().select();
				tb_caixa.setModel(new ItemCaixaTableModel(itens));
				
				if (!itens.isEmpty()) {
					double total = itens.stream().map((t) -> {
						return t.getQuantidade() * t.getProduto().getValor();
					}).reduce((t, u) -> {
						return t.doubleValue() + u.doubleValue(); //To change body of generated lambdas, choose Tools | Templates.
					}).get();

					tx_total.setText(NumberFormat.getCurrencyInstance(ptBR).format(total));
				} else {
					tx_total.setText(NumberFormat.getCurrencyInstance(ptBR).format(0));
				}
			} break;
			case 1: { // PRODUTOS
				final ArrayList<Produto> produtos = ProdutoDAO.get().select();
				tb_produtos.setModel(new ProdutoTableModel(produtos));
			}
			break;
		}
    }//GEN-LAST:event_tabsStateChanged

    private void bt_add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_add1ActionPerformed
        if (tx_pnome.getText().trim().isEmpty()) {
			JOptionPane.showMessageDialog(this, "Campo NOME não pode estar vazio.", "Erro", JOptionPane.ERROR_MESSAGE);
			return;
		}
		if (tx_valor.getText().trim().isEmpty()) {
			JOptionPane.showMessageDialog(this, "Campo VALOR não pode estar vazio.", "Erro", JOptionPane.ERROR_MESSAGE);
			return;
		}
		
		Produto prod = new Produto();
		prod.setNome(tx_pnome.getText());
		prod.setDescricao(tx_pdesc.getText());
		prod.setValor(((Number) tx_valor.getValue()).doubleValue());
		ProdutoDAO.get().insert(prod);
		tabsStateChanged(null);
    }//GEN-LAST:event_bt_add1ActionPerformed

    private void tb_produtosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_produtosMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON3) {
			pm_tablecell_produtos.show(evt.getComponent(), evt.getX(), evt.getY());
		}
    }//GEN-LAST:event_tb_produtosMouseClicked

    private void mn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_deleteActionPerformed
        if (tb_produtos.getSelectedRow()!= -1) {
			ProdutoDAO.get().delete(((ProdutoTableModel)tb_produtos.getModel()).getData().get(tb_produtos.getSelectedRow()));
			tabsStateChanged(null);
		}
    }//GEN-LAST:event_mn_deleteActionPerformed

    private void mn_delete_cxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_delete_cxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mn_delete_cxActionPerformed

    private void bt_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addActionPerformed
		ItemCaixa p = new ItemCaixa();
		p.setProduto((Produto) sp_produtos.getSelectedItem());
		p.setQuantidade((int) sp_qtd.getValue());
		ItemCaixaDAO.get().insert(p);
		tabsStateChanged(null);
    }//GEN-LAST:event_bt_addActionPerformed

	private JPanel getMoneyInput() {
		JPanel panel = new JPanel();
		JFormattedTextField tx_valor = new JFormattedTextField(
				new DefaultFormatterFactory(
						new NumberFormatter(NumberFormat.getCurrencyInstance(ptBR)),
						new NumberFormatter(NumberFormat.getCurrencyInstance(ptBR)),
						new NumberFormatter(NumberFormat.getNumberInstance())
				)
		);
		
		panel.setLayout(new BorderLayout(6, 6));
		panel.add(tx_valor, BorderLayout.CENTER);
				
		return panel;
	}

    private void bt_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_fecharActionPerformed
		final ArrayList<ItemCaixa> itens = ItemCaixaDAO.get().select();
		double total = itens.stream().map((t) -> {
				return t.getQuantidade() * t.getProduto().getValor();
			}).reduce((t, u) -> {
				return t.doubleValue() + u.doubleValue(); //To change body of generated lambdas, choose Tools | Templates.
			}).get();
		
		final JPanel panel = getMoneyInput();
		int res = JOptionPane.showConfirmDialog(this,
                        panel,
                        "Valor Pago",
                        JOptionPane.OK_CANCEL_OPTION,
                        JOptionPane.PLAIN_MESSAGE);
		
		if (res == JOptionPane.OK_OPTION) {
			for (ItemCaixa i : itens) {
				ItemCaixaDAO.get().fecha(i.getId());
			}
			tabsStateChanged(null);
			
			try {
				double troco = ((Number) tx_valor.getValue()).doubleValue() - total;
				String trocoText = ("Troco: " + NumberFormat.getCurrencyInstance(ptBR).format(troco));
				JOptionPane.showMessageDialog(this, trocoText, "Finalizado", JOptionPane.INFORMATION_MESSAGE);
			} catch (Exception ex) {

			}
		}
    }//GEN-LAST:event_bt_fecharActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainForm().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_add;
    private javax.swing.JButton bt_add1;
    private javax.swing.JButton bt_fechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenuItem mn_delete;
    private javax.swing.JMenuItem mn_delete_cx;
    private javax.swing.JPopupMenu pm_tablecell_caixa;
    private javax.swing.JPopupMenu pm_tablecell_produtos;
    private javax.swing.JComboBox<Produto> sp_produtos;
    private javax.swing.JSpinner sp_qtd;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tb_caixa;
    private javax.swing.JTable tb_produtos;
    private javax.swing.JTextField tx_pdesc;
    private javax.swing.JTextField tx_pnome;
    private javax.swing.JLabel tx_total;
    private javax.swing.JFormattedTextField tx_valor;
    // End of variables declaration//GEN-END:variables
}
